### Numpy
- stands for numerical python
- is a python library package to support numerical computations
- the basic data structure in numpy is a multi-dimensional array object called nd array
- provides a suite of functions that can efficiently manipuate elements of the ndarray

1. Create an ndarray  
An ndarray can be created from a list or tuple object

In [2]:
import numpy as np

In [3]:
# a one-dimensional array (vector)
oneDim = np.array([1.0, 2, 3, 4, 5])

print(oneDim)
print('Number of dimensions: ', oneDim.ndim)
print('Dimension: ', oneDim.shape)
print('Size: ', oneDim.size)
print('Array type: ', oneDim.dtype)

[1. 2. 3. 4. 5.]
Number of dimensions:  1
Dimension:  (5,)
Size:  5
Array type:  float64


In [4]:
# a two-dimensional array (matrix)
twoDim = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])

print(twoDim)
print('Number of dimensions: ', twoDim.ndim)
print('Dimension: ', twoDim.shape)
print('Size: ', twoDim.size)
print('Array type: ', twoDim.dtype)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Number of dimensions:  2
Dimension:  (4, 2)
Size:  8
Array type:  int64


In [5]:
# create ndarray from tuple
arrFromTuple = np.array([(1, 'a', 3.0), (2, 'b', 3.5)])

print(arrFromTuple)
print('Number of dimensions: ', arrFromTuple.ndim)
print('Dimension: ', arrFromTuple.shape)
print('Size: ', arrFromTuple.size)

[['1' 'a' '3.0']
 ['2' 'b' '3.5']]
Number of dimensions:  2
Dimension:  (2, 3)
Size:  6


In [6]:
# add 1 to every item in the list
# traditional method:
nums = [1, 2, 3, 4, 5]
for x in range(len(nums)):
  nums[x] += 1
print(nums)

# using numpy (easier syntax)
x = np.array([1, 2, 3, 4, 5])
print(x + 1)

[2, 3, 4, 5, 6]
[2 3 4 5 6]


There are several built-in functions in numpy that can be used to create ndarrays

In [7]:
# random numbers from a uniform distribution between [0, 1]
print(np.random.rand(5))

[0.61582604 0.18426995 0.47070813 0.35922439 0.52908695]


In [8]:
# random numbers from a normal distribution
print(np.random.randn(5))

[-0.5695875  -0.61842287  2.69991667  1.94303258 -2.12722356]


In [9]:
# similar to range but returns ndarray instead of list
print(np.arange(-10, 10, 2))

[-10  -8  -6  -4  -2   0   2   4   6   8]


In [10]:
# reshape to a matrix
print(np.arange(12).reshape(3, 4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [11]:
# split interval [0, 1] into 10 equally separated values
print(np.linspace(0, 1, 10))

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [12]:
# create ndarray with values from 19^-3 to 10^3
print(np.logspace(-3, 3, 7))

[1.e-03 1.e-02 1.e-01 1.e+00 1.e+01 1.e+02 1.e+03]


In [13]:
# a matrix of zeros
print(np.zeros((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [14]:
# a matrix of ones
print(np.ones((3, 2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [15]:
# a 3 x 3 identity matrix
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


2. Element-wise Operations
Standard operators (such as addition and multiplication) can be applied to each element of the ndarray

In [16]:
x = np.array([1, 2, 3, 4, 5])

print('x + 1:', x + 1)
print('x - 1:', x - 1)
print('x * 2:', x * 2)
print('x // 2: ', x // 2)
print('x ** 2: ', x ** 2)
print('x % 2: ', x % 2)
print('1 / x: ', 1 / x)

x + 1: [2 3 4 5 6]
x - 1: [0 1 2 3 4]
x * 2: [ 2  4  6  8 10]
x // 2:  [0 1 1 2 2]
x ** 2:  [ 1  4  9 16 25]
x % 2:  [1 0 1 0 1]
1 / x:  [1.         0.5        0.33333333 0.25       0.2       ]


In [17]:
x = np.array([2, 4, 6, 8, 10])
y = np.array([1, 2, 3, 4, 5])

print('x + y: ', x + y)
print('x - y:' , x - y)
print('x * y:' , x * y)
print('x / y: ', x / y)
print('x // y: ', x // y)
print('x ** y: ', x ** y)

x + y:  [ 3  6  9 12 15]
x - y: [1 2 3 4 5]
x * y: [ 2  8 18 32 50]
x / y:  [2. 2. 2. 2. 2.]
x // y:  [2 2 2 2 2]
x ** y:  [     2     16    216   4096 100000]


3. Indexing and Slicing  
There are various ways to select certain elements with an ndarray

In [18]:
x = np.arange(-5,5)
print(x)
print()

y = x[3:5]     # y is a slice, i.e., pointer to a subarray in x
print(y)
print()

y[:] = 1000    # modifying the value of y will change x
print(y)
print(x)
print()

z = x[3:5].copy()   # makes a copy of the subarray
print(z)
print()

z[:] = 500          # modifying the value of z will not affect x
print(z)
print(x)

[-5 -4 -3 -2 -1  0  1  2  3  4]

[-2 -1]

[1000 1000]
[  -5   -4   -3 1000 1000    0    1    2    3    4]

[1000 1000]

[500 500]
[  -5   -4   -3 1000 1000    0    1    2    3    4]


In [19]:
my2dlist = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]   # a 2-dim list
print(my2dlist)
print(my2dlist[2])        # access the third sublist
print(my2dlist[:][2])     # can't access third element of each sublist
# print(my2dlist[:,2])    # this will cause syntax error
print()

my2darr = np.array(my2dlist)
print(my2darr)
print(my2darr[2][:])      # access the third row
print(my2darr[2,:])       # access the third row
print(my2darr[:][2])      # access the third row (similar to 2d list)
print(my2darr[:,2])       # access the third column
print(my2darr[:2,2:])     # access the first two rows & last two columns

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[9, 10, 11, 12]
[9, 10, 11, 12]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 9 10 11 12]
[ 9 10 11 12]
[ 9 10 11 12]
[ 3  7 11]
[[3 4]
 [7 8]]


In [20]:
# ndarray also supports boolean indexing
my2darr = np.arange(1,13,1).reshape(3,4)
print(my2darr)
print()

divBy3 = my2darr[my2darr % 3 == 0]
print(divBy3, type(divBy3))
print()

divBy3LastRow = my2darr[2:, my2darr[2,:] % 3 == 0]
print(divBy3LastRow)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[ 3  6  9 12] <class 'numpy.ndarray'>

[[ 9 12]]


In [21]:
my2darr = np.arange(1, 13, 1).reshape(4, 3)
print(my2darr)
print()

indices = [2, 1, 0, 3]  # selected row indices
print(my2darr[indices, :])
print()

rowIndex = [0, 0, 1, 2, 3]  # row index into my2darr
columnIndex = [0, 2, 0, 1, 2]   # column index into my2darr
print(my2darr[rowIndex, columnIndex])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 7  8  9]
 [ 4  5  6]
 [ 1  2  3]
 [10 11 12]]

[ 1  3  4  8 12]


4. Numpy Arithmetic and Statistical Functions  
There are many built-in mathematical functions available for manipulating elements of nd-array

In [22]:
y = np.array([-1.4, 0.4, -3.2, 2.5, 3.4])    # generate a random vector

print('y: ', y)
print('np.abs(y): ', np.abs(y))                 # convert to absolute values
print('np.sqrt(abs(y)): ', np.sqrt(abs(y)))     # apply square root to each element
print('np.sign(y): ', np.sign(y))               # get the sign of each element
print('np.exp(y): ', np.exp(y))                 # apply exponentiation
print('np.sort(y): ', np.sort(y))               # sort array

y:  [-1.4  0.4 -3.2  2.5  3.4]
np.abs(y):  [1.4 0.4 3.2 2.5 3.4]
np.sqrt(abs(y)):  [1.18321596 0.63245553 1.78885438 1.58113883 1.84390889]
np.sign(y):  [-1.  1. -1.  1.  1.]
np.exp(y):  [ 0.24659696  1.4918247   0.0407622  12.18249396 29.96410005]
np.sort(y):  [-3.2 -1.4  0.4  2.5  3.4]


In [23]:
x = np.arange(-2,3)
y = np.random.randn(5)

print('x: ', x)
print('y: ', y)
print('np.add(x,y):', np.add(x,y))                  # element-wise addition       x + y
print('np.subtract(x,y): ', np.subtract(x,y))       # element-wise subtraction    x - y
print('np.multiply(x,y): ', np.multiply(x,y))       # element-wise multiplication x * y
print('np.divide(x,y): ', np.divide(x,y))           # element-wise division       x / y
print('np.maximum(x,y): ', np.maximum(x,y))         # element-wise maximum        max(x,y)

x:  [-2 -1  0  1  2]
y:  [1.17005905 1.17053837 1.24176474 0.097143   0.27426361]
np.add(x,y): [-0.82994095  0.17053837  1.24176474  1.097143    2.27426361]
np.subtract(x,y):  [-3.17005905 -2.17053837 -1.24176474  0.902857    1.72573639]
np.multiply(x,y):  [-2.3401181  -1.17053837  0.          0.097143    0.54852722]
np.divide(x,y):  [-1.70931544 -0.85430775  0.         10.29410229  7.2922544 ]
np.maximum(x,y):  [1.17005905 1.17053837 1.24176474 1.         2.        ]


In [24]:
y = np.array([-3.2, -1.4, 0.4, 2.5, 3.4])    # generate a random vector

print('y: ', y)
print("Min = ", np.min(y))             # min 
print("Max = ", np.max(y))             # max 
print("Average = ", np.mean(y))        # mean/average
print("Std deviation = ", np.std(y))   # standard deviation
print("Sum = ", np.sum(y))             # sum 

y:  [-3.2 -1.4  0.4  2.5  3.4]
Min =  -3.2
Max =  3.4
Average =  0.34000000000000014
Std deviation =  2.432776191925595
Sum =  1.7000000000000006


5. Numpy linear algebra  
numpy provides many functions to linear algebra operations

In [25]:
x = np.random.randn(2, 3)   # create a 2 x 3 random matrix
print(x)
print(x.T)    # matrix transpose operation x^T
print()

y = np.random.randn(3)  # random vector
print(y)
print(x.dot(y))   # matrix-vector multiplication x * y
print(x.dot(x.T))   # matrix-vector multiplication x * x^T 
print(x.T.dot(x))   # matrix-vector multiplication x^T * x


[[-1.04136751 -1.78793478  1.45984447]
 [ 0.85571091 -0.5610175  -1.38290455]]
[[-1.04136751  0.85571091]
 [-1.78793478 -0.5610175 ]
 [ 1.45984447 -1.38290455]]

[-0.63105977  1.41436681 -1.79448242]
[-4.49129572  1.14810865]
[[ 6.41230293 -1.9068724 ]
 [-1.9068724   2.95940679]]
[[ 1.81668744  1.38182839 -2.7036011 ]
 [ 1.38182839  3.5114514  -1.83427304]
 [-2.7036011  -1.83427304  4.04357088]]


In [26]:
X = np.random.randn(5, 3)
print(X)
print()

C = X.T.dot(X)    # C = X^T * X is a square matrix

invC = np.linalg.inv(C)   # inverse of a square matrix
print(invC)
print()

detC = np.linalg.det(C)  # determinant of a square matrix
print(detC)
print()

S, U = np.linalg.eig(C)   # eigenvalue S and eigenvector U of a square matrix
print(S)
print(U)

[[-0.34111081  0.47014131  1.27691673]
 [-0.61603161  0.71028791  0.44931613]
 [-1.21743282  0.24438383 -0.33592068]
 [-0.91156003 -0.60284323  2.17729227]
 [-1.17993387 -0.73473113 -0.16599002]]

[[ 0.29002413 -0.07136725  0.08663305]
 [-0.07136725  0.61638909  0.01018929]
 [ 0.08663305  0.01018929  0.17649176]]

38.65507754355633

[7.94861499 3.07082542 1.58365276]
[[ 0.49501733  0.84339282 -0.20891718]
 [ 0.0899622   0.18940173  0.9777698 ]
 [-0.86421331  0.50280765 -0.01788366]]
