### Numpy
- stands for numerical python
- is a python library package to support numerical computations
- the basic data structure in numpy is a multi-dimensional array object called nd array
- provides a suite of functions that can efficiently manipuate elements of the ndarray

1. Create an ndarray  
An ndarray can be created from a list or tuple object

In [1]:
import numpy as np

In [2]:
# a one-dimensional array (vector)
oneDim = np.array([1.0, 2, 3, 4, 5])

print(oneDim)
print('Number of dimensions: ', oneDim.ndim)
print('Dimension: ', oneDim.shape)
print('Size: ', oneDim.size)
print('Array type: ', oneDim.dtype)

[1. 2. 3. 4. 5.]
Number of dimensions:  1
Dimension:  (5,)
Size:  5
Array type:  float64


In [3]:
# a two-dimensional array (matrix)
twoDim = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])

print(twoDim)
print('Number of dimensions: ', twoDim.ndim)
print('Dimension: ', twoDim.shape)
print('Size: ', twoDim.size)
print('Array type: ', twoDim.dtype)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Number of dimensions:  2
Dimension:  (4, 2)
Size:  8
Array type:  int64


In [4]:
# create ndarray from tuple
arrFromTuple = np.array([(1, 'a', 3.0), (2, 'b', 3.5)])

print(arrFromTuple)
print('Number of dimensions: ', arrFromTuple.ndim)
print('Dimension: ', arrFromTuple.shape)
print('Size: ', arrFromTuple.size)

[['1' 'a' '3.0']
 ['2' 'b' '3.5']]
Number of dimensions:  2
Dimension:  (2, 3)
Size:  6


There are several built-in functions in numpy that can be used to create ndarrays

In [5]:
# random numbers from a uniform distribution between [0, 1]
print(np.random.rand(5))

[0.96638802 0.94774151 0.16307861 0.18827542 0.07469565]


In [6]:
# random numbers from a normal distribution
print(np.random.randn(5))

[ 0.9126412  -1.4887677   2.11805209 -0.31422528  0.4598256 ]


In [8]:
# similar to range but returns ndarray instead of list
print(np.arange(-10, 10, 2))

[-10  -8  -6  -4  -2   0   2   4   6   8]


In [9]:
# reshape to a matrix
print(np.arange(12).reshape(3, 4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [11]:
# split interval [0, 1] into 10 equally separated values
print(np.linspace(0, 1, 10))

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [12]:
# create ndarray with values from 19^-3 to 10^3
print(np.logspace(-3, 3, 7))

[1.e-03 1.e-02 1.e-01 1.e+00 1.e+01 1.e+02 1.e+03]


In [13]:
# a matrix of zeros
print(np.zeros((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
# a matrix of ones
print(np.ones((3, 2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [16]:
# a 3 x 3 identity matrix
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


2. Element-wise Operations
Standard operators (such as addition and multiplication) can be applied to each element of the ndarray

In [20]:
x = np.array([1, 2, 3, 4, 5])

print('x + 1:', x + 1)
print('x - 1:', x - 1)
print('x * 2:', x * 2)
print('x // 2: ', x // 2)
print('x ** 2: ', x ** 2)
print('x % 2: ', x % 2)
print('1 / x: ', 1 / x)

x + 1: [2 3 4 5 6]
x - 1: [0 1 2 3 4]
x * 2: [ 2  4  6  8 10]
x // 2:  [0 1 1 2 2]
x ** 2:  [ 1  4  9 16 25]
x % 2:  [1 0 1 0 1]
1 / x:  [1.         0.5        0.33333333 0.25       0.2       ]


In [21]:
x = np.array([2, 4, 6, 8, 10])
y = np.array([1, 2, 3, 4, 5])

print('x + y: ', x + y)
print('x - y:' , x - y)
print('x * y:' , x * y)
print('x / y: ', x / y)
print('x // y: ', x // y)
print('x ** y: ', x ** y)

x + y:  [ 3  6  9 12 15]
x - y: [1 2 3 4 5]
x * y: [ 2  8 18 32 50]
x / y:  [2. 2. 2. 2. 2.]
x // y:  [2 2 2 2 2]
x ** y:  [     2     16    216   4096 100000]


3. Indexing and Slicing  
There are various ways to select certain elements with an ndarray

In [28]:
x = np.arange(-5,5)
print(x)
print()

y = x[3:5]     # y is a slice, i.e., pointer to a subarray in x
print(y)
print()

y[:] = 1000    # modifying the value of y will change x
print(y)
print(x)
print()

z = x[3:5].copy()   # makes a copy of the subarray
print(z)
print()

z[:] = 500          # modifying the value of z will not affect x
print(z)
print(x)

[-5 -4 -3 -2 -1  0  1  2  3  4]

[-2 -1]

[1000 1000]
[  -5   -4   -3 1000 1000    0    1    2    3    4]

[1000 1000]

[500 500]
[  -5   -4   -3 1000 1000    0    1    2    3    4]


In [29]:
my2dlist = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]   # a 2-dim list
print(my2dlist)
print(my2dlist[2])        # access the third sublist
print(my2dlist[:][2])     # can't access third element of each sublist
# print(my2dlist[:,2])    # this will cause syntax error
print()

my2darr = np.array(my2dlist)
print(my2darr)
print(my2darr[2][:])      # access the third row
print(my2darr[2,:])       # access the third row
print(my2darr[:][2])      # access the third row (similar to 2d list)
print(my2darr[:,2])       # access the third column
print(my2darr[:2,2:])     # access the first two rows & last two columns

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[9, 10, 11, 12]
[9, 10, 11, 12]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 9 10 11 12]
[ 9 10 11 12]
[ 9 10 11 12]
[ 3  7 11]
[[3 4]
 [7 8]]


In [30]:
# ndarray also supports boolean indexing
my2darr = np.arange(1,13,1).reshape(3,4)
print(my2darr)
print()

divBy3 = my2darr[my2darr % 3 == 0]
print(divBy3, type(divBy3))
print()

divBy3LastRow = my2darr[2:, my2darr[2,:] % 3 == 0]
print(divBy3LastRow)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[ 3  6  9 12] <class 'numpy.ndarray'>

[[ 9 12]]


In [24]:
my2darr = np.arange(1, 13, 1).reshape(4, 3)
print(my2darr)
print()

indices = [2, 1, 0, 3]  # selected row indices
print(my2darr[indices, :])
print()

rowIndex = [0, 0, 1, 2, 3]  # row index into my2darr
columnIndex = [0, 2, 0, 1, 2]   # column index into my2darr
print(my2darr[rowIndex, columnIndex])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 7  8  9]
 [ 4  5  6]
 [ 1  2  3]
 [10 11 12]]

[ 1  3  4  8 12]


4. Numpy Arithmetic and Statistical Functions  
There are many built-in mathematical functions available for manipulating elements of nd-array

In [31]:
y = np.array([-1.4, 0.4, -3.2, 2.5, 3.4])    # generate a random vector

print('y: ', y)
print('np.abs(y): ', np.abs(y))                 # convert to absolute values
print('np.sqrt(abs(y)): ', np.sqrt(abs(y)))     # apply square root to each element
print('np.sign(y): ', np.sign(y))               # get the sign of each element
print('np.exp(y): ', np.exp(y))                 # apply exponentiation
print('np.sort(y): ', np.sort(y))               # sort array

y:  [-1.4  0.4 -3.2  2.5  3.4]
np.abs(y):  [1.4 0.4 3.2 2.5 3.4]
np.sqrt(abs(y)):  [1.18321596 0.63245553 1.78885438 1.58113883 1.84390889]
np.sign(y):  [-1.  1. -1.  1.  1.]
np.exp(y):  [ 0.24659696  1.4918247   0.0407622  12.18249396 29.96410005]
np.sort(y):  [-3.2 -1.4  0.4  2.5  3.4]


In [35]:
x = np.arange(-2,3)
y = np.random.randn(5)

print('x: ', x)
print('y: ', y)
print('np.add(x,y):', np.add(x,y))                  # element-wise addition       x + y
print('np.subtract(x,y): ', np.subtract(x,y))       # element-wise subtraction    x - y
print('np.multiply(x,y): ', np.multiply(x,y))       # element-wise multiplication x * y
print('np.divide(x,y): ', np.divide(x,y))           # element-wise division       x / y
print('np.maximum(x,y): ', np.maximum(x,y))         # element-wise maximum        max(x,y)

x:  [-2 -1  0  1  2]
y:  [ 1.42579703  1.85467765  0.41756659  0.53079137 -0.80198784]
np.add(x,y): [-0.57420297  0.85467765  0.41756659  1.53079137  1.19801216]
np.subtract(x,y):  [-3.42579703 -2.85467765 -0.41756659  0.46920863  2.80198784]
np.multiply(x,y):  [-2.85159407 -1.85467765  0.          0.53079137 -1.60397568]
np.divide(x,y):  [-1.4027242  -0.53917725  0.          1.88397939 -2.4938034 ]
np.maximum(x,y):  [1.42579703 1.85467765 0.41756659 1.         2.        ]


In [33]:
y = np.array([-3.2, -1.4, 0.4, 2.5, 3.4])    # generate a random vector

print('y: ', y)
print("Min = ", np.min(y))             # min 
print("Max = ", np.max(y))             # max 
print("Average = ", np.mean(y))        # mean/average
print("Std deviation = ", np.std(y))   # standard deviation
print("Sum = ", np.sum(y))             # sum 

y:  [-3.2 -1.4  0.4  2.5  3.4]
Min =  -3.2
Max =  3.4
Average =  0.34000000000000014
Std deviation =  2.432776191925595
Sum =  1.7000000000000006


5. Numpy linear algebra  
numpy provides many functions to linear algebra operations

In [25]:
x = np.random.randn(2, 3)   # create a 2 x 3 random matrix
print(x)
print(x.T)    # matrix transpose operation x^T
print()

y = np.random.randn(3)  # random vector
print(y)
print(x.dot(y))   # matrix-vector multiplication x * y
print(x.dot(x.T))   # matrix-vector multiplication x * x^T 
print(x.T.dot(x))   # matrix-vector multiplication x^T * x


[[ 0.15897895 -0.45632667 -0.47878324]
 [ 1.25701341 -0.96765393 -0.46467511]]
[[ 0.15897895  1.25701341]
 [-0.45632667 -0.96765393]
 [-0.47878324 -0.46467511]]

[-0.30242631 -0.92689634  0.00249402]
[0.37369401 0.51560204]
[[0.46274172 0.86388362]
 [0.86388362 2.7323598 ]]
[[ 1.60535702 -1.2889003  -0.6602193 ]
 [-1.2889003   1.14458815  0.66812625]
 [-0.6602193   0.66812625  0.44515635]]


In [27]:
X = np.random.randn(5, 3)
print(X)
print()

C = X.T.dot(X)    # C = X^T * X is a square matrix

invC = np.linalg.inv(C)   # inverse of a square matrix
print(invC)
print()

detC = np.linalg.det(C)  # determinant of a square matrix
print(detC)
print()

S, U = np.linalg.eig(C)   # eigenvalue S and eigenvector U of a square matrix
print(S)
print(U)

[[-0.50408507  0.92706794 -0.51839068]
 [ 0.23470674  0.74577024  0.74729468]
 [-1.11263451  0.3041946  -1.72323774]
 [ 0.01317934 -0.49443978  0.94386069]
 [ 0.16882209 -0.24097901 -1.05121274]]

[[ 1.55537029  0.38380995 -0.54398118]
 [ 0.38380995  0.67097487 -0.06849398]
 [-0.54398118 -0.06849398  0.37038656]]

6.4628137858247285

[6.87479357 0.52972184 1.77465566]
[[ 0.3947768  -0.89341155 -0.21439933]
 [-0.17065836 -0.30059556  0.93835922]
 [ 0.90278846  0.33385342  0.27113631]]
